#!/bin/bash

set -x
set -e
set -u

export PATH=${PATH}:~/.local/bin:/c/Users/$(whoami)/.local/bin

mkdir -p ../build
cd ../build
cmake ../SCROOM-plugin-cpp -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX="../scroom-installed/scroom" -DENABLE_CACHE=OFF

cmake --build . -j2
( . ENVIRONMENT && ctest -j2 )

cmake --build . --target package_source -j2
mv ScroomCPPPlugins-*Source.tar.gz ../SCROOM-plugin-cpp

cmake --install .
../scroom/build_scripts/windows/post-install-cmake-hook.sh ../scroom-installed/scroom
cd ../scroom-installed

SCROOM_VERSION="$(cat ../scroom/.scroom-version)"
SCROOM_NAME="scroom-win-${SCROOM_VERSION}"
zip -r "../scroom/${SCROOM_NAME}.zip" scroom
