#ifndef SCROOM_PLUGIN_CPP_PLUGINS_SEP_PARSING_SEPPARSERPRESENTATION_HH_
#define SCROOM_PLUGIN_CPP_PLUGINS_SEP_PARSING_SEPPARSERPRESENTATION_HH_

class sepparserpresentation{
public:
	sepparserpresentation();
	virtual ~sepparserpresentation();
};

#endif /* SCROOM_PLUGIN_CPP_PLUGINS_SEP_PARSING_SEPPARSERPRESENTATION_HH_ */
