#ifndef SCROOM_PLUGIN_CPP_PLUGINS_SEP_PARSING_SEP_PARSER_HH_
#define SCROOM_PLUGIN_CPP_PLUGINS_SEP_PARSING_SEP_PARSER_HH_

class SepParser {
public:
	SepParser();
	virtual ~SepParser();
};

#endif /* SCROOM_PLUGIN_CPP_PLUGINS_SEP_PARSING_SEP_PARSER_HH_ */
