#!/bin/bash

#useful for debugging but will leak secret variables on Travis for Windows
#set -x
set -e
set -u

#first build the Scroom repository
chmod -R 755 scroom
cd scroom
autoreconf -i
cd ..

scroom_loc=$(pwd)/build/scroom
plugin_loc=$(pwd)/build/plugin-build

mkdir scroom-build
cd scroom-build

../scroom/configure --prefix $scroom_loc
make -k -j2 install
cd ..

#build the plugins
autoreconf -i

mkdir cpp-plugins-build
cd cpp-plugins-build

../configure --prefix=$plugin_loc CPPFLAGS=-I$scroom_loc/include/ LDFLAGS="-L$scroom_loc/lib"
make -k -j2 install

if [ "${TRAVIS_OS_NAME}" = "windows" ]
then
  #for windows we can build a portable application with all the plugins
  rm -rf $scroom_loc
  cd ../scroom-build

  make -k -j2 install-win-portable
  
  cp -rf $plugin_loc/lib/bin/* $scroom_loc/plugins/
  cd $scroom_loc
  cd ..
  zip -r scroom.zip scroom
  
  artifact=./scroom.zip
  name=scroom.zip
else
  #the linux build is not portable so we only provide the plugins
  cd $plugin_loc
  cd ..
  mkdir plugins
  cp -rf plugin-build/lib/scroom/* plugins/
  zip -r plugins-linux.zip plugins

  artifact=./plugins-linux.zip
  name=plugins-linux.zip
fi

ls -l

#if this build is for a tag add the build artifacts as GitHub release artifacts
if [ ! "${TRAVIS_TAG}" = "" ]
then
  tag_id=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases/tags/$TRAVIS_TAG | jq '.id')
  curl --data-binary @"$artifact" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/octet-stream" "https://uploads.github.com/repos/$TRAVIS_REPO_SLUG/releases/$tag_id/assets?name=$name"
fi