#!/bin/bash

set -x
set -e
set -u

git clone --depth 200 https://github.com/kees-jan/scroom.git
cd scroom

autoreconf -i

cd ..

scroom_loc=$(pwd)/scroom-install
plugin_loc=$(pwd)/plugin-build

mkdir scroom-build
cd scroom-build

../scroom/configure --prefix $scroom_loc
make -k -j2 install
cd ..

autoreconf -i

mkdir cpp-plugins-build
cd cpp-plugins-build

../configure --prefix=$plugin_loc CPPFLAGS=-I$scroom_loc/include/ LDFLAGS="-L$scroom_loc/lib"
make -k -j2 install

if [ "${TRAVIS_OS_NAME}" = "windows" ]
then
  rm -rf $scroom_loc
  cd scroom-build

  make -k -j2 install-win-portable
  
  cd ..
  cp -r $(plugin_loc)/lib/bin/ $(scroom_loc)/plugins/
  zip -r scroom.zip $scroom_loc
  
  curl --data-binary @"./scroom.zip" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/octet-stream" "https://uploads.github.com/repos/$TRAVIS_REPO_SLUG/releases/27564671/assets?name=scroom.zip"
else
  tar czf ./plugins-linux.tar.gz $plugin_loc

  curl --data-binary @"./plugins-linux.tar.gz" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/octet-stream" "https://uploads.github.com/repos/$TRAVIS_REPO_SLUG/releases/27564671/assets?name=plugins-linux.tar.gz"
fi

ls -l