#!/bin/bash

set -x
set -e
set -u

plugins_source=$1
plugins_build=$2
prefix=$3

cd "${plugins_build}"
"${plugins_source}"/configure --prefix "${prefix}" \
                   CPPFLAGS="-I${prefix}/include/" LDFLAGS="-L${prefix}/lib"
make -k -j2 install
