#!/bin/bash

#useful for debugging but will leak secret variables on Travis for Windows
# set -x
set -e
set -u

scroom_source="$1"
# scroom_build="$2"
# plugins_source="$3"
# plugins_build="$4"
prefix="$5"

scroom_version=$(cat "${scroom_source}/.scroom-version")
plugins_version=$(cat ".project-version")
zip_name="scroom_${scroom_version}_cpp-plugins_${plugins_version}.zip"
artifact="/tmp/${zip_name}"

( cd "${prefix}/.." && zip -r "/tmp/${zip_name}" . )

if [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
 [ "${TRAVIS_REPO_SLUG}" = "SCROOM-plugin-cpp/SCROOM-plugin-cpp" ] &&
 [ "${TRAVIS_TAG}" != "" ]
then
  tag_id=$(curl -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases/tags/$TRAVIS_TAG" | jq '.id')
  curl --data-binary @"$artifact" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/octet-stream" "https://uploads.github.com/repos/$TRAVIS_REPO_SLUG/releases/$tag_id/assets?name=$zip_name"
fi
